### ISSUE TITLE
SSL error Install Mac 12.4

### ISSUE THREAD

**Issue by Cryptonoobie333** [AsahiLinux/asahi-installer#103] opened 2022-06-14 15:25 UTC
Hey guys, keep getting this error. Looks like a network issue but I'm not technical enough to see what's happening. Could anyone help me out? Thanks in advance :)
<img width="1635" alt="Schermafbeelding 2022-06-14 om 16 53 23" src="https://user-images.githubusercontent.com/107278460/173615957-fa4f109e-a29f-4f12-bed9-051ba00ae89c.png">

**Comment by gomidee** [comment] 2022-06-15 01:16
Same here....

**Comment by op06072** [comment] 2022-06-15 07:54
I make the script that can fix the error.
[https://github.com/op06072/asahi-linux-ssl-fix/blob/master/asahi-fix.sh](url)

You can run with command

`curl -L https://vo.la/vVrDXw | sh`
this.

**Comment by Cryptonoobie333** [comment] 2022-06-15 12:34
> I make the script that can fix the error. `https://github.com/op06072/asahi-linux-ssl-fix/blob/master/asahi-fix.sh`
> 
> You can run with command `curl -L https://vo.la/vVrDXw | sh` this.
> 
> ![스크린샷 2022-06-15 오후 4 56 24](https://user-images.githubusercontent.com/60420877/173774672-25717bcf-56db-4233-96c4-dfe7a1bdfc78.png) I add a python module and one line to init function of urlcache.py script. This change make that installer can work even with Apple CDN's unverified ssl.
> 
> ![스크린샷 2022-06-15 오후 4 57 23](https://user-images.githubusercontent.com/60420877/173775472-d70cf1f8-a8f7-40c4-9a09-1b68eeeeff48.png)
> 
> and finally I can install the asahi-linux.
> 
> ![KakaoTalk_Photo_2022-06-15-17-05-40](https://user-images.githubusercontent.com/60420877/173775811-83a4fc1b-ea77-4682-a942-bdc327a1c4d3.jpeg) ![KakaoTalk_Photo_2022-06-15-17-05-53](https://user-images.githubusercontent.com/60420877/173775822-0cbd5a35-cebe-4b38-b33e-bf97a17e18d8.png)

Worked! Thank you :)

**Comment by flexv99** [comment] 2022-06-16 09:10
You don't have to skip verification, just install or update the default root certs for the ssl module, using [this](https://gist.github.com/yelled3/a5eaf3ca90011aaf7e7901c55680ff06) link.

**Comment by op06072** [comment] 2022-06-16 09:46
> 확인을 건너뛸 필요가 없습니다 . [이](https://gist.github.com/yelled3/a5eaf3ca90011aaf7e7901c55680ff06) 링크를 사용하여 ssl 모듈의 기본 루트 인증서를 설치하거나 업데이트하기만 하면 됩니다.

That link use macOS internal python but we need python which downloded with installer.

**Comment by marcan** [comment] 2022-06-21 08:35
Duplicate of #101

**Closed by marcan** 2022-06-21 08:35 UTC
