### ISSUE TITLE
Failed to run process: diskutil apfs resizeContainer disk0s2 413999824896

### ISSUE THREAD

**Issue by milanmdev** [AsahiLinux/asahi-installer#113] opened 2022-07-16 04:17 UTC
When trying to install Asahi, I run into the following error: `Failed to run process: diskutil apfs resizeContainer disk0s2 413999824896`.

Here's the full output:
```log
Failed to run process: diskutil apfs resizeContainer disk0s2 413999824896
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 820, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 672, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 792, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 612, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '413999824896']' returned non-zero exit status 1.
```

**Comment by marcan** [comment] 2022-10-25 10:28
Duplicate of #81

**Closed by marcan** 2022-10-25 10:28 UTC
