### ISSUE TITLE
Install Error MacOS 12.4

### ISSUE THREAD

**Issue by notdezzi** [AsahiLinux/asahi-installer#102] opened 2022-06-14 11:36 UTC
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/8899318/installer.log)

**Comment by Cryptonoobie333** [comment] 2022-06-14 15:34
Having the same problem, just opened an issue as well

**Comment by op06072** [comment] 2022-06-15 07:55
I make the script that can fix the error.
[https://github.com/op06072/asahi-linux-ssl-fix/blob/master/asahi-fix.sh](url)

You can run with command

`curl -L https://vo.la/vVrDXw | sh`
this.

**Comment by marcan** [comment] 2022-06-21 08:29
Please do not direct people to use scripts which disable security. SSL validation fails for a reason.

**Comment by marcan** [comment] 2022-06-21 08:35
Duplicate of #102

**Closed by marcan** 2022-06-21 08:35 UTC
