### ISSUE TITLE
./build.sh: line 52: cd: /Users/<username>/asahi-installer/package/Frameworks/Python.framework/Versions/Current: No such file or directory

### ISSUE THREAD

**Issue by ghost** [AsahiLinux/asahi-installer#9] opened 2022-01-16 11:45 UTC
Hello, i encountered an error when i try to build asahi-installer on my m1 mac at (read title, and screen for more details)
<img width="682" alt="image" src="https://user-images.githubusercontent.com/63967691/149658525-b66d09cd-2231-4846-b229-e18bcd396b69.png">

**Comment by aviwad** [comment] 2022-03-18 09:05
i manually unzipped the Python installer PKG, copied the relevant file to the folder and ran rest of the build.sh commands myself

**Comment by marcan** [comment] 2022-04-11 12:56
Duplicate of #3

**Closed by marcan** 2022-04-11 12:56 UTC
