### ISSUE TITLE
Add an option to uninstall Asahi or instructions in the docs

### ISSUE THREAD

**Issue by CMDR-Piboy314** [AsahiLinux/asahi-installer#62] opened 2022-03-23 14:22 UTC
I installed Asahi on my machine just to test a few things and go back to MacOS. I gave it 70Gb to test games and such. Now I can't give the space back to my main drive. Adding an option in the installer to uninstall it would be helpful for people who need that in the future. But for me, I've messed with my partitions and such so much that whatever's added probably wouldn't help me at the moment. Here's a link to my [stackoverflow question](https://apple.stackexchange.com/questions/438794/i-cant-delete-storage-containers-from-my-disk) if you can help (please do as I need more space on my main drive now as I only have a base model.) @marcan

**Comment by maximalisms** [comment] 2022-03-24 21:17
Absolutely agree. Or consider warning users the resize is rather complicated (for newer users) to reverse. Less technical users would have a pretty tough time figuring out how to get their disk back to where it was.

**Comment by marcan** [comment] 2022-03-24 21:23
We're going to add an uninstall option in the future, but it'll necessarily be limited in what cases it can handle, since there's no magic way of safely handling every possible partitioning state and users can make their own changes from Linux or do completely different things using third-party installers launched from UEFI mode.

In the meantime, I wrote up a guide on how the partitioning works [here](https://github.com/AsahiLinux/docs/wiki/Partitioning-cheatsheet). Does that help?

**Comment by marcan** [comment] 2022-03-27 06:43
It will work, but you'd have to move the Asahi partitions upwards into the free space before you can resize the Asahi root partition. That can't be done while the system is booted into Linux, and diskutil won't move partitions for you, so you'd have to use some kind of live Linux recovery environment. I want to offer our users something like that for this and other reasons :)

**Comment by marcan** [comment] 2022-04-11 12:51
Tracking this in #83 now.

Duplicate of #83

**Comment by marcan** [comment] 2022-04-11 12:51
Duplicate of #83

**Closed by marcan** 2022-04-11 12:51 UTC
