### ISSUE TITLE
Certificate verification failure

### ISSUE THREAD

**Issue by op06072** [AsahiLinux/asahi-installer#101] opened 2022-06-14 10:18 UTC
![스크린샷 2022-06-14 오후 7 14 47](https://user-images.githubusercontent.com/60420877/173554294-70076a69-2ea2-4192-b7c5-e18130c61ce0.png)
![스크린샷 2022-06-14 오후 7 15 52](https://user-images.githubusercontent.com/60420877/173554311-437c9ebd-756a-4a20-8a43-979f7ef060db.png)

My macbook is on macOS 12.4 but installer uses 12.3. How can I install with 12.4?

**Comment by jannau** [comment] 2022-06-14 18:06
AsahiLinux uses parts of macOS 12.3 for the installation. This are boot files (firmware) and a macOS recovery image. These parts are necessary to convince iBoot that there is OS installtion. The mismatch in the versions is not a problem as it is not a problem to install macOS 12.3 on system which has 12.4 already installed.

The problem in this case seems to be that TLS certificate verification for Apple's CDN fails.

**Comment by marcan** [comment] 2022-06-21 08:59
I cannot reproduce this. Please run this command and paste the full output: `openssl s_client -showcerts -connect updates.cdn-apple.com:443 < /dev/null`

It would also be helpful if you listed your country and network type (residential, corporate, educational).

**Comment by op06072** [comment] 2022-06-22 00:24
> I cannot reproduce this. Please run this command and paste the full output: `openssl s_client -showcerts -connect updates.cdn-apple.com:443 < /dev/null`
> 
> It would also be helpful if you listed your country and network type (residential, corporate, educational).

CONNECTED(00000006)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
verify return:1
depth=0 CN = updates.cdn-apple.com, O = Apple Inc., ST = California, C = US
verify return:1
---
Certificate chain
 0 s:CN = updates.cdn-apple.com, O = Apple Inc., ST = California, C = US
   i:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
-----BEGIN CERTIFICATE-----
MIIICDCCBvCgAwIBAgIQWHe/1nukG6m/X7o9jPAeRDANBgkqhkiG9w0BAQsFADBi
MRwwGgYDVQQDExNBcHBsZSBJU1QgQ0EgMiAtIEcxMSAwHgYDVQQLExdDZXJ0aWZp
Y2F0aW9uIEF1dGhvcml0eTETMBEGA1UEChMKQXBwbGUgSW5jLjELMAkGA1UEBhMC
VVMwHhcNMjExMTE3MDI0ODU2WhcNMjIxMjE3MDI0ODU1WjBXMR4wHAYDVQQDDBV1
cGRhdGVzLmNkbi1hcHBsZS5jb20xEzARBgNVBAoMCkFwcGxlIEluYy4xEzARBgNV
BAgMCkNhbGlmb3JuaWExCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAtfIvwR0yp5WRIqJuOlSOf1kD058lMxV84wamr2XBamj+2/Lx
pyf9k8tSSbSwizSx14ZLFr1PCXpszRYY3QlCZhZ65WviI1//A5kplQX2xGj0AGVL
D/uW0HIWqn8vfPb6hpBVfh6s4OFkxAdBKpnn7fuiiZ1iOnNaH+3nJLd6K78a9fcQ
ZzfTXeTSBpRQdH94f9d/h4kfV0geFZxZKDHe3mwop6E+B0pajOEAZe5JHL3sTwaC
/4NhPZbiN2lxWLvhX+jvvKKPDisvWtpkUuplFaHIq/hHon2s5p3KGUYbu+fBe5PU
/b2ukUru7seEM5MKIwyCVwFnOrZ1aRMsl3+iKwIDAQABo4IEwzCCBL8wDAYDVR0T
AQH/BAIwADAfBgNVHSMEGDAWgBTYepREfJBwkBae3RecAUQDhtYqKTCBuQYIKwYB
BQUHAQEEgawwgakwNwYIKwYBBQUHMAKGK2h0dHA6Ly9jZXJ0cy5hcHBsZS5jb20v
YXBwbGVpc3RjYTJnMV9iYy5jZXIwNAYIKwYBBQUHMAKGKGh0dHA6Ly9jZXJ0cy5h
cHBsZS5jb20vYXBwbGVpc3RjYTJnMS5kZXIwOAYIKwYBBQUHMAGGLGh0dHA6Ly9v
Y3NwLmFwcGxlLmNvbS9vY3NwMDMtYXBwbGVpc3RjYTJnMTI3MCAGA1UdEQQZMBeC
FXVwZGF0ZXMuY2RuLWFwcGxlLmNvbTCCAQcGA1UdIASB/zCB/DAIBgZngQwBAgIw
ge8GCiqGSIb3Y2QFCwQwgeAwNwYIKwYBBQUHAgEWK2h0dHBzOi8vd3d3LmFwcGxl
LmNvbS9jZXJ0aWZpY2F0ZWF1dGhvcml0eS8wgaQGCCsGAQUFBwICMIGXDIGUUmVs
aWFuY2Ugb24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBh
Y2NlcHRhbmNlIG9mIGFueSBhcHBsaWNhYmxlIHRlcm1zIGFuZCBjb25kaXRpb25z
IG9mIHVzZSBhbmQvb3IgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRz
LjATBgNVHSUEDDAKBggrBgEFBQcDATA3BgNVHR8EMDAuMCygKqAohiZodHRwOi8v
Y3JsLmFwcGxlLmNvbS9hcHBsZWlzdGNhMmcxLmNybDAdBgNVHQ4EFgQUJncP5LXl
SRO18kBkDPOPpq3oQREwDgYDVR0PAQH/BAQDAgWgMCwGCiqGSIb3Y2QGMAEEHgwc
MS4yLjg0MC4xMTM2MzUuMTAwLjYuMjcuNDAuMjCCAfgGCisGAQQB1nkCBAIEggHo
BIIB5AHiAHcAUaOw9f0BeZxWbbg3eI8MpHrMGyfL956IQpoN/tSLBeUAAAF9K9VD
BQAABAMASDBGAiEAjUJ1wY9WLvDMs7YkAJo3kxwWbh25wxBZH/NPcPSczS4CIQDx
x0Zw2d41QsMqj1QlPsa8pC7ACinIRLTf2WJJksbABQB2ACl5vvCeOTkh8FZzn2Ol
d+W+V32cYAr4+U1dJlwlXceEAAABfSvVQmUAAAQDAEcwRQIhAMS2YRn9dbmgG8+Z
e4ra7OUQwOfX6yp+GgfFaQ5m/n1kAiAVbijdwvIWFDBW2F0/Df8Ih8o//Oh14kKo
PHvEckVr2QB3AEHIyrHfIkZKEMahOglCh15OMYsbA+vrS8do8JBilgb2AAABfSvV
QqYAAAQDAEgwRgIhAP0ZRlDhW9o3wcheDnmbttnpwOUQD34dlFqfA3KFIv5yAiEA
r4RN+z/cjFWk+1ai/csbaRXf9sgSySmIGPTAevLqEYEAdgDfpV6raIJPH2yt7rhf
Tj5a6s2iEqRqXo47EsAgRFwqcwAAAX0r1ULUAAAEAwBHMEUCIQDsXihjpBVRrZd4
rBXb0Co435B5H0SlWjLNLo6Wn4gZrgIgfSlVsbVaBv5m5y56N+4biJeTXQow5CEp
RWnDfyztrYIwDQYJKoZIhvcNAQELBQADggEBAKxHkLCzRynwzJVWjcuamHvljp+d
SLKaKpYgc8xI3ktoXOG56On1XmSJY7zAy++RdG6t9y6H7VroF3EdfGSC8bqO69GN
WPFOs9Jw2OmM6cXuaZzozg2jIExrvDOZ4OMadqH1N7b5A/biyO15jPAbh3PIT56x
l0AZx76LPbfZ0bcSvHeTsvZLtwLpfh5Q46bxQFcTpV2yvwWYM8hSsLgRwAddh88A
jPIvCLyGewijgevR80lRXsk4oOKeqRYy8BPrKZfLp7dBb177938MMuuznsWekISL
HLOXg4ErZzhd2U371thzVlC25MVuyBe7FAtDWEb3BPAmvsHRHZ9NBGLgScw=
-----END CERTIFICATE-----
 1 s:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
   i:C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
-----BEGIN CERTIFICATE-----
MIIEnjCCA4agAwIBAgIQBVLH7/7sKSup8Th7B6+SnzANBgkqhkiG9w0BAQsFADBa
MQswCQYDVQQGEwJJRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJl
clRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTE4
MTIxMjEyMDAwMFoXDTI1MDUwNzEyMDAwMFowYjEcMBoGA1UEAxMTQXBwbGUgSVNU
IENBIDIgLSBHMTEgMB4GA1UECxMXQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzAR
BgNVBAoTCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEA0JOhHUdDIBayC2vrw9W06MeYzfPev+hN6eM2gAf8RRtq
fEWGrlbTpAl/YQ1rXX5Sa320yDnE9Gc694POGW+GL35FfkccZ1LKlQVd4jZRhcDU
Z4A1bxXdPv0d0v2PNFDY7HYqvuPT2uT9yOsoApYRlxdhHOnEWTtC3DLRCR3aptFD
hv9esryMz2bbAYsCrpRI8ziP/eoyqAjshpdRlCQ+SUmWU+h5oUCB6QW7k5VR/OP9
fBFL954IsxVJFQf50Tegm0sy9rXE3GrR/Art9uDFKaCoi3H+DZK8/lRwGAptx+0M
+8ktBsOMhfzLhlzWNo4Siwl/+xkaONXwlDB6D6aM8wIDAQABo4IBVjCCAVIwHQYD
VR0OBBYEFNh6lER8kHCQFp7dF5wBRAOG1iopMB8GA1UdIwQYMBaAFOWdWTCCR1jM
rPoIVDaGezq1BE3wMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcD
AQYIKwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADA0BggrBgEFBQcBAQQoMCYw
JAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTA6BgNVHR8EMzAx
MC+gLaArhilodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vT21uaXJvb3QyMDI1LmNy
bDBbBgNVHSAEVDBSMAwGCiqGSIb3Y2QFCwQwCAYGZ4EMAQICMDgGCmCGSAGG/WwA
AgQwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAN
BgkqhkiG9w0BAQsFAAOCAQEAWgDobaZ4Dq8zSOdyWvCa+Tad60OIwE9qkz2o33KF
CcAM/CvxXrcXTTYo9VJHninE+G9SguIdukkDDAOHMT8WvsqomydMXknQJVbREOAX
KUKgS5q0/9ou9N1FjJvkhPGFzAbuLnSJtLomfJPxHW4h3l6bdliQodVQXd3xUbXR
qTKNUbF9bIh4601+KhyZL0u0B/eTppf/1O5S+qFAyRADr1lvfIeNHZv11iyf4u7e
uLBsXjyT3vPwxrihpAwB5pu/DhJWh4iv70Q7pcvAaRRfiJgMj3A0fFgvqvGbW9jm
t04+Cr/PjpWeMFt3KKj3DRh4jJKjJUGt+JxdGGJ4tCGyCw==
-----END CERTIFICATE-----
---
Server certificate
subject=CN = updates.cdn-apple.com, O = Apple Inc., ST = California, C = US

issuer=CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3795 bytes and written 387 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
DONE

**Comment by marcan** [comment] 2022-06-26 03:23
Let's call this a duplicate of #107

**Closed by marcan** 2022-06-26 03:23 UTC
