### ISSUE TITLE
Disk resizing error

### ISSUE THREAD

**Issue by Ilfeni** [AsahiLinux/asahi-installer#80] opened 2022-04-02 04:18 UTC
I was installing Asahi and when I arrived at the disk resizing part I was confronted to this message:
Failed to run process: diskutil apfs resizeContainer disk0s2 429998997504
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 820, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 672, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 792, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 612, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '429998997504']' returned non-zero exit status 1.
If you need to file a bug report, please attach the log file
What can I do
ps: I tried first aid on the disk it didn't work

**Comment by marcan** [comment] 2022-04-11 12:44
Duplicate of #81.

**Closed by marcan** 2022-04-11 12:44 UTC
