### ISSUE TITLE
Installer is failing to resize a partition of a fresh MacBook air2.

### ISSUE THREAD

**Issue by leitao** [AsahiLinux/asahi-installer#143] opened 2022-10-18 09:39 UTC
The installer failed with :

`subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '51847888896']' returned non-zero exit status 1.
`

I've just bought a MacBook Air m2, and straight away tried to install Asahi linux:

```
Last login: Mon Oct 17 17:45:35 on console
brenoleitao@Brenos-MacBook-Air ~ % curl https://alx.sh | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1440  100  1440    0     0    628      0  0:00:02  0:00:02 --:--:--   630

Bootstrapping installer:
  Checking version...
  Version: v0.4.1
  Downloading...
^[[B^[[B^[[B^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
Password:
Sorry, try again.
Password:

Welcome to the Asahi Linux installer!

This installer is in an alpha state, and may not work for everyone.
It is intended for developers and early adopters who are comfortable
debugging issues or providing detailed bug reports.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.


By default, this installer will hide certain advanced options that
are only useful for developers. You can enable expert mode to show them.
» Enable expert mode? (y/N): y

Collecting system information...
  Product name: MacBook Air (M2, 2022)
  SoC: Apple M2
  Device class: j413ap
  Product type: Mac14,2
  Board ID: 0x28
  Chip ID: 0x8112
  System firmware: iBoot-7459.141.1
  Boot UUID: 25D691E7-1CFD-4993-922E-DC0617A8107C
  Boot VGID: 25D691E7-1CFD-4993-922E-DC0617A8107C
  Default boot VGID: 25D691E7-1CFD-4993-922E-DC0617A8107C
  Boot mode: macOS
  OS version: 12.5.1 (21G83)
  SFR version: 21.7.83.0.0,0
  System rOS version: 12.5.1 (21G83)
  No Fallback rOS
  Login user: brenoleitao

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (245.11 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v12.5.1 [disk3s1, 25D691E7-1CFD-4993-922E-DC0617A8107C]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v12.5.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (r): r


Choose an existing partition to resize:
  1: APFS [Macintosh HD] (245.11 GB, 6 volumes)
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
» Partition: 
Enter one of the following: 1, 2
» Partition: 1

We're going to resize this partition:
  APFS [Macintosh HD] (245.11 GB, 6 volumes)
  Total size: 245.11 GB
  Free space: 194.26 GB
  Minimum free space: 1.00 GB
  Minimum total size: 51.85 GB (21.15%)

Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (50%): min

Resizing will free up 193.26 GB of space.

Note: your system may appear to freeze during the resize.
This is normal, just wait until the process completes.
» Continue? (y/N): y

Started APFS operation
Aligning shrink delta to 193,259,307,008 bytes and targeting a new physical store size of 51,847,888,896 bytes
Determined the minimum size for the targeted physical store of this APFS Container to be 53,234,106,368 bytes
Error: -69521: Your APFS Container resize request is below the APFS-system-imposed minimal container size (perhaps caused by APFS Snapshot usage by Time Machine)
Failed to run process: diskutil apfs resizeContainer disk0s2 51847888896
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 852, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 704, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 824, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 635, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '51847888896']' returned non-zero exit status 1.
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log

```

**Comment by leitao** [comment] 2022-10-18 09:42
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/9809014/installer.log)

**Comment by leitao** [comment] 2022-10-18 09:47
When I try to call again the installer, I get:

```
brenoleitao@Brenos-MacBook-Air ~ % curl https://alx.sh | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1440  100  1440    0     0   1616      0 --:--:-- --:--:-- --:--:--  1621

Bootstrapping installer:
  Checking version...
  Version: v0.4.1
  Downloading...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
Password:

Welcome to the Asahi Linux installer!

This installer is in an alpha state, and may not work for everyone.
It is intended for developers and early adopters who are comfortable
debugging issues or providing detailed bug reports.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.


By default, this installer will hide certain advanced options that
are only useful for developers. You can enable expert mode to show them.
» Enable expert mode? (y/N): y

Collecting system information...
  Product name: MacBook Air (M2, 2022)
  SoC: Apple M2
  Device class: j413ap
  Product type: Mac14,2
  Board ID: 0x28
  Chip ID: 0x8112
  System firmware: iBoot-7459.141.1
  Boot UUID: 25D691E7-1CFD-4993-922E-DC0617A8107C
  Boot VGID: 25D691E7-1CFD-4993-922E-DC0617A8107C
  Default boot VGID: 25D691E7-1CFD-4993-922E-DC0617A8107C
  Boot mode: macOS
  OS version: 12.5.1 (21G83)
  SFR version: 21.7.83.0.0,0
  System rOS version: 12.5.1 (21G83)
  No Fallback rOS
  Login user: brenoleitao

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (245.11 GB, 6 volumes)
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v12.5.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Unable to determine primary OS.
This installer requires you to already have a macOS install with
at least one administrator user that is a machine owner.
Please run this installer from your main macOS instance or its
paired recovery, or ensure the default boot volume is set correctly.
```

**Comment by leitao** [comment] 2022-10-18 10:20
Documenting what I am trying, so, we have a track history:

I've tried to repair all the 3 partitions that the disk has, following the suggestion from: https://support.apple.com/en-us/HT210898

No luck so far.

The summary is, we might have two bugs:

1) The installer is corrupting the Mac filesystem (AFS) (Is this being tracked anywhere?)
2) The installer get stuck when the file system is corrupted (This is being tracked at https://github.com/AsahiLinux/asahi-installer/issues/81)

**Comment by marcan** [comment] 2022-10-18 11:49
You're way off the mark :). Your shiny new machine has a pending macOS update. Install it, and try the Asahi installer again.

The reason why this breaks is that it 1) uses temporary disk space that is not accounted for normally, which breaks the installer's calculations for minimum safe size (if you read the first log closely, you'll see that's all it was), and 2) at some point it makes your "live" root filesystem contents inconsistent with any macOS version (your system is running from a snapshot), so the installer can't figure out what macOS version is installed (your second failure).

No corruption, just a corner case we don't handle yet.

**Comment by leitao** [comment] 2022-10-18 13:58
Thanks @marcan .

> your system is running from a snapshot

How come I got running in a snapshot file system? I am just booting a default Mac OS X with time capsule disabled (since this is the default in Mac OS X, AFAIK).
This also happens after I reboot the machine.

**Comment by marcan** [comment] 2022-10-18 16:24
Because that's how macOS works. macOS always runs from a snapshot of the immutable System partition. In fact, the macOS kernel has a check and will panic if you try to boot it from the live filesystem instead of a blessed snapshot.

The installer just looks at the live filesystem to find macOS instances, and that is inconsistent when there is a pending upgrade (it would match the snapshot after the upgrade completes).

**Comment by marcan** [comment] 2022-10-25 10:13
Duplicate of #86

**Closed** 2022-10-25 10:13 UTC
