### ISSUE TITLE
Fresh install requests `_mbsetupuser` pwd to bless

### ISSUE THREAD

**Issue by SjonHortensius** [AsahiLinux/asahi-installer#174] opened 2023-02-01 08:15 UTC
I just bought a new Macbook Air specifically for running archlinux through this amazing project. The first thing I did after unwrapping was run the asahi installer - which worked fine until I hit a bump. Although previous steps requested my fresh `user` password and accepted it, while running `bless` the installer suddenly requested the password for a user called `_mbsetupuser`. I tried a few passwords but nothing got accepted.

```
To continue the installation, you will need to enter your macOS
admin credentials.

Password for _mbsetupuser: 

Setting the new OS as the default boot volume...
Bootability failed Error Domain=BYErrorDomain Code=103 "Owner authentication is required" UserInfo={BYErrorHint=LocalAuthenticationRequired, NSLocalizedDescription=Owner authentication is required}
Failed to run bless. Press enter to try again.

```
[log stream --process BootabilityService --process bless output](https://github.com/AsahiLinux/asahi-installer/files/10554902/bless.log)

I can't really think of a reason, I did look for a firmware update while running the installer (but hadn't even started downloading that) and this mba is fresh from the factory on it's first boot.

It seems this is not a known issue, and I'd love to help fix it. I worked around by installing from recovery after applying the firmware update

**Comment by marcan** [comment] 2023-02-02 02:31
I assume you no longer have the installer log from `/tmp/asahi-install/installer.log`? Without that it's very hard to figure out what went wrong :(

**Comment by SjonHortensius** [comment] 2023-02-02 09:17
no - unfortunately not. Maybe store that in a persistent directory (even `~/Desktop`?) after a failure, or mention that location in the error? I did look around for existing issues, that's why I ran the `log stream`. Hopefully if anyone else experiences this they will be able to upload that log

**Comment by marcan** [comment] 2023-02-07 04:48
OK, I think I know what happened here. I can't reproduce it, but I see how it could've happened on a fresh machine randomly. The problem is that `scutil` shows two logged in users (but only one marked "on console"), and we don't currently try to select the right one in any reasonable way. It probably would've worked fine if you just rebooted the machine back into macOS, since I think `_mbsetupuser` only gets logged in for the initial setup wizard.

**Comment by SjonHortensius** [comment] 2023-02-16 12:17
if I had any python skills I would propose a fix - it seems you are right and the best fix is to change https://github.com/AsahiLinux/asahi-installer/blob/2e64e3fc7e8a774f57eee2a3b82e6dd1ba409393/src/system.py#L79-L80

where the static `[1]` should become a loop over all logged in users, skipping an users whose name start with `_`

**Comment by Crejan** [comment] 2023-03-20 19:41
same issue. here is a log file

[installer.log](https://github.com/AsahiLinux/asahi-installer/files/11022394/installer.log)

**Comment by Gadgetoid** [comment] 2023-06-15 23:23
Also ran across this for the same reason- fresh install, no reboot.

I'm not up to speed with macOS, but is there any reason it can't just do:

```python
self.login_user = os.environ.get("SUDO_USER")
```

Since in (all, I hope?) cases it should be present:

```
sudo env | grep SUDO_USER
SUDO_USER=foobar
```

I think the current approach has another potential failure mode where another non-root user, or a user you lack the password for is logged in.

**Comment by marcan** [comment] 2023-10-08 18:30
Should be fixed now.

**Closed by marcan** 2023-10-08 18:30 UTC
