### ISSUE TITLE
Asahi installer claims system firmware is too old on developer beta firmware

### ISSUE THREAD

**Issue by Kara-Zor-El** [AsahiLinux/asahi-installer#214] opened 2023-09-19 18:28 UTC
Hi, so as the title says, I am running MacOS Sonoma (14.0 (23A339)) and am getting reports that the firmware is too old despite it not being old
here is the installer log
I am using expert mode due to being on a M2 Pro device but due to this being a issue with you just not including the firmware rather signature rather than it doing something incorrectly or not working, figured id file just in case
[installer.log](https://github.com/AsahiLinux/asahi-installer/files/12665303/installer.log)

**Comment by jannau** [comment] 2023-09-19 18:47
This is a misleading error message. The issue is that none of the OS images is  marked as supporting macOS 13.5 as stub partition which is required for M2 Pro/Max/Ultra devices. The fedora-asahi-remix installer avoids this issue but the main issue is that the devices are not yet fully supported.

**Comment by marcan** [comment] 2023-10-08 18:23
(Not) working as intended. Images will be updated with 13.5 firmware once these machines are promoted to supported.

**Closed by marcan** 2023-10-08 18:23 UTC
